### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by PatrickAlphaC** [dmfxyz/murky#17]
gm!

Would love to see some versioning in this so users can install it as a foundry package!

**Comment by danielmfinn** [comment]
Hey! Good thought. I can add that over the weekend.

**Comment by dmfxyz** [comment]
Very true sir. I will introduce versioning in the next couple days!

**Comment by yorhodes** [comment]
struggling with remappings when attempting to install as a foundry package

**Comment by dmfxyz** [comment]
Hi -- apologies for the delay here. I have published a version tag / release on github. Let me know if this is satisfactory.

**Comment by PatrickAlphaC** [comment]
This is great!
