### ISSUE TITLE
Add package.json pls

### ISSUE THREAD

**Issue by AndriyAntonenko** [dmfxyz/murky#20]
In our project, we use Foundry for development, but we prefer managing dependencies with Bun as it simplifies the process. It would be great if a package.json file could be added for the Murky library. Murky is a unique library that allows us to generate Merkle trees using Solidity, and having a package.json would make it easier to integrate and manage within our existing workflow.

**Comment by PaulRBerg** [comment]
cc @dmfxyz could you please add a `package.json` file? Or accept a PR that adds it? It's a simple change that would make it possible to install this repo as a Node.js dependency.

**Comment by dmfxyz** [comment]
@PaulRBerg Thanks for flagging. I am happy to accept a PR that adds one. Or add myself. I'm not familiar with using this for solidity dependency management, what should the contents of this file be?

**Comment by PaulRBerg** [comment]
Thanks @dmfxyz.

A minimal `package.json` file like the one found in Forge Std would suffice:

https://github.com/foundry-rs/forge-std/blob/master/package.json
